/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndexOldRouteImport } from './routes/index.old'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSugestoesRouteImport } from './routes/_authenticated/sugestoes'
import { Route as AuthenticatedPermissoesRouteImport } from './routes/_authenticated/permissoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedOperadoresRouteImport } from './routes/_authenticated/operadores'
import { Route as AuthenticatedIntegracaoBempRouteImport } from './routes/_authenticated/integracao-bemp'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedConfiguracaoWhatsappRouteImport } from './routes/_authenticated/configuracao-whatsapp'
import { Route as AuthenticatedBoasVindasRouteImport } from './routes/_authenticated/boas-vindas'
import { Route as AuthenticatedBaseConhecimentoRouteImport } from './routes/_authenticated/base-conhecimento'
import { Route as AuthenticatedAuditoriaSugestoesRouteImport } from './routes/_authenticated/auditoria-sugestoes'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedAssinantesRouteImport } from './routes/_authenticated/assinantes'
import { Route as AuthenticatedAprendizadoIaRouteImport } from './routes/_authenticated/aprendizado-ia'
import { Route as AuthenticatedAgentesWhatsappRouteImport } from './routes/_authenticated/agentes-whatsapp'
import { Route as AuthenticatedAgendarRouteImport } from './routes/_authenticated/agendar'
import { Route as AuthenticatedAcessosRouteImport } from './routes/_authenticated/acessos'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicWhatsappEvolutionRouteImport } from './routes/api/public/whatsapp-evolution'
import { Route as ApiPublicWhatsappRouteImport } from './routes/api/public/whatsapp'
import { Route as ApiPublicTestIaRouteImport } from './routes/api/public/test-ia'
import { Route as ApiPublicCrmCronRouteImport } from './routes/api/public/crm-cron'
import { Route as ApiPublicBempWebhookRouteImport } from './routes/api/public/bemp-webhook'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicWhatsappEvolutionTestRouteImport } from './routes/api/public/whatsapp-evolution/test'
import { Route as ApiPublicWhatsappEvolutionHealthRouteImport } from './routes/api/public/whatsapp-evolution/health'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksWhatsappHealthRouteImport } from './routes/api/public/hooks/whatsapp-health'
import { Route as ApiPublicHooksLembretesRouteImport } from './routes/api/public/hooks/lembretes'
import { Route as ApiPublicHooksLearningPatternsRouteImport } from './routes/api/public/hooks/learning-patterns'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexOldRoute = IndexOldRouteImport.update({
  id: '/index/old',
  path: '/index/old',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSugestoesRoute = AuthenticatedSugestoesRouteImport.update({
  id: '/sugestoes',
  path: '/sugestoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissoesRoute = AuthenticatedPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperadoresRoute = AuthenticatedOperadoresRouteImport.update({
  id: '/operadores',
  path: '/operadores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracaoBempRoute =
  AuthenticatedIntegracaoBempRouteImport.update({
    id: '/integracao-bemp',
    path: '/integracao-bemp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracaoWhatsappRoute =
  AuthenticatedConfiguracaoWhatsappRouteImport.update({
    id: '/configuracao-whatsapp',
    path: '/configuracao-whatsapp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoasVindasRoute = AuthenticatedBoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaseConhecimentoRoute =
  AuthenticatedBaseConhecimentoRouteImport.update({
    id: '/base-conhecimento',
    path: '/base-conhecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaSugestoesRoute =
  AuthenticatedAuditoriaSugestoesRouteImport.update({
    id: '/auditoria-sugestoes',
    path: '/auditoria-sugestoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinantesRoute = AuthenticatedAssinantesRouteImport.update({
  id: '/assinantes',
  path: '/assinantes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAprendizadoIaRoute =
  AuthenticatedAprendizadoIaRouteImport.update({
    id: '/aprendizado-ia',
    path: '/aprendizado-ia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentesWhatsappRoute =
  AuthenticatedAgentesWhatsappRouteImport.update({
    id: '/agentes-whatsapp',
    path: '/agentes-whatsapp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendarRoute = AuthenticatedAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcessosRoute = AuthenticatedAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappEvolutionRoute =
  ApiPublicWhatsappEvolutionRouteImport.update({
    id: '/api/public/whatsapp-evolution',
    path: '/api/public/whatsapp-evolution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappRoute = ApiPublicWhatsappRouteImport.update({
  id: '/api/public/whatsapp',
  path: '/api/public/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestIaRoute = ApiPublicTestIaRouteImport.update({
  id: '/api/public/test-ia',
  path: '/api/public/test-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmCronRoute = ApiPublicCrmCronRouteImport.update({
  id: '/api/public/crm-cron',
  path: '/api/public/crm-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBempWebhookRoute = ApiPublicBempWebhookRouteImport.update({
  id: '/api/public/bemp-webhook',
  path: '/api/public/bemp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappEvolutionTestRoute =
  ApiPublicWhatsappEvolutionTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => ApiPublicWhatsappEvolutionRoute,
  } as any)
const ApiPublicWhatsappEvolutionHealthRoute =
  ApiPublicWhatsappEvolutionHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => ApiPublicWhatsappEvolutionRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappHealthRoute =
  ApiPublicHooksWhatsappHealthRouteImport.update({
    id: '/api/public/hooks/whatsapp-health',
    path: '/api/public/hooks/whatsapp-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLembretesRoute = ApiPublicHooksLembretesRouteImport.update({
  id: '/api/public/hooks/lembretes',
  path: '/api/public/hooks/lembretes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksLearningPatternsRoute =
  ApiPublicHooksLearningPatternsRouteImport.update({
    id: '/api/public/hooks/learning-patterns',
    path: '/api/public/hooks/learning-patterns',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/agendar': typeof AuthenticatedAgendarRoute
  '/agentes-whatsapp': typeof AuthenticatedAgentesWhatsappRoute
  '/aprendizado-ia': typeof AuthenticatedAprendizadoIaRoute
  '/assinantes': typeof AuthenticatedAssinantesRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/auditoria-sugestoes': typeof AuthenticatedAuditoriaSugestoesRoute
  '/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/configuracao-whatsapp': typeof AuthenticatedConfiguracaoWhatsappRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/integracao-bemp': typeof AuthenticatedIntegracaoBempRoute
  '/operadores': typeof AuthenticatedOperadoresRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/sugestoes': typeof AuthenticatedSugestoesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/index/old': typeof IndexOldRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/bemp-webhook': typeof ApiPublicBempWebhookRoute
  '/api/public/crm-cron': typeof ApiPublicCrmCronRoute
  '/api/public/test-ia': typeof ApiPublicTestIaRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/api/public/whatsapp-evolution': typeof ApiPublicWhatsappEvolutionRouteWithChildren
  '/api/public/hooks/learning-patterns': typeof ApiPublicHooksLearningPatternsRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
  '/api/public/hooks/whatsapp-health': typeof ApiPublicHooksWhatsappHealthRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp-evolution/health': typeof ApiPublicWhatsappEvolutionHealthRoute
  '/api/public/whatsapp-evolution/test': typeof ApiPublicWhatsappEvolutionTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/agendar': typeof AuthenticatedAgendarRoute
  '/agentes-whatsapp': typeof AuthenticatedAgentesWhatsappRoute
  '/aprendizado-ia': typeof AuthenticatedAprendizadoIaRoute
  '/assinantes': typeof AuthenticatedAssinantesRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/auditoria-sugestoes': typeof AuthenticatedAuditoriaSugestoesRoute
  '/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/configuracao-whatsapp': typeof AuthenticatedConfiguracaoWhatsappRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/integracao-bemp': typeof AuthenticatedIntegracaoBempRoute
  '/operadores': typeof AuthenticatedOperadoresRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/sugestoes': typeof AuthenticatedSugestoesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/index/old': typeof IndexOldRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/bemp-webhook': typeof ApiPublicBempWebhookRoute
  '/api/public/crm-cron': typeof ApiPublicCrmCronRoute
  '/api/public/test-ia': typeof ApiPublicTestIaRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/api/public/whatsapp-evolution': typeof ApiPublicWhatsappEvolutionRouteWithChildren
  '/api/public/hooks/learning-patterns': typeof ApiPublicHooksLearningPatternsRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
  '/api/public/hooks/whatsapp-health': typeof ApiPublicHooksWhatsappHealthRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp-evolution/health': typeof ApiPublicWhatsappEvolutionHealthRoute
  '/api/public/whatsapp-evolution/test': typeof ApiPublicWhatsappEvolutionTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/acessos': typeof AuthenticatedAcessosRoute
  '/_authenticated/agendar': typeof AuthenticatedAgendarRoute
  '/_authenticated/agentes-whatsapp': typeof AuthenticatedAgentesWhatsappRoute
  '/_authenticated/aprendizado-ia': typeof AuthenticatedAprendizadoIaRoute
  '/_authenticated/assinantes': typeof AuthenticatedAssinantesRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/auditoria-sugestoes': typeof AuthenticatedAuditoriaSugestoesRoute
  '/_authenticated/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/_authenticated/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/_authenticated/configuracao-whatsapp': typeof AuthenticatedConfiguracaoWhatsappRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/integracao-bemp': typeof AuthenticatedIntegracaoBempRoute
  '/_authenticated/operadores': typeof AuthenticatedOperadoresRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/permissoes': typeof AuthenticatedPermissoesRoute
  '/_authenticated/sugestoes': typeof AuthenticatedSugestoesRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/index/old': typeof IndexOldRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/bemp-webhook': typeof ApiPublicBempWebhookRoute
  '/api/public/crm-cron': typeof ApiPublicCrmCronRoute
  '/api/public/test-ia': typeof ApiPublicTestIaRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/api/public/whatsapp-evolution': typeof ApiPublicWhatsappEvolutionRouteWithChildren
  '/api/public/hooks/learning-patterns': typeof ApiPublicHooksLearningPatternsRoute
  '/api/public/hooks/lembretes': typeof ApiPublicHooksLembretesRoute
  '/api/public/hooks/whatsapp-health': typeof ApiPublicHooksWhatsappHealthRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp-evolution/health': typeof ApiPublicWhatsappEvolutionHealthRoute
  '/api/public/whatsapp-evolution/test': typeof ApiPublicWhatsappEvolutionTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/acessos'
    | '/agendar'
    | '/agentes-whatsapp'
    | '/aprendizado-ia'
    | '/assinantes'
    | '/assinatura'
    | '/auditoria-sugestoes'
    | '/base-conhecimento'
    | '/boas-vindas'
    | '/configuracao-whatsapp'
    | '/crm'
    | '/integracao-bemp'
    | '/operadores'
    | '/painel'
    | '/perfil'
    | '/permissoes'
    | '/sugestoes'
    | '/usuarios'
    | '/api/chat'
    | '/api/transcribe'
    | '/api/tts'
    | '/checkout/return'
    | '/index/old'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/bemp-webhook'
    | '/api/public/crm-cron'
    | '/api/public/test-ia'
    | '/api/public/whatsapp'
    | '/api/public/whatsapp-evolution'
    | '/api/public/hooks/learning-patterns'
    | '/api/public/hooks/lembretes'
    | '/api/public/hooks/whatsapp-health'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp-evolution/health'
    | '/api/public/whatsapp-evolution/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/acessos'
    | '/agendar'
    | '/agentes-whatsapp'
    | '/aprendizado-ia'
    | '/assinantes'
    | '/assinatura'
    | '/auditoria-sugestoes'
    | '/base-conhecimento'
    | '/boas-vindas'
    | '/configuracao-whatsapp'
    | '/crm'
    | '/integracao-bemp'
    | '/operadores'
    | '/painel'
    | '/perfil'
    | '/permissoes'
    | '/sugestoes'
    | '/usuarios'
    | '/api/chat'
    | '/api/transcribe'
    | '/api/tts'
    | '/checkout/return'
    | '/index/old'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/bemp-webhook'
    | '/api/public/crm-cron'
    | '/api/public/test-ia'
    | '/api/public/whatsapp'
    | '/api/public/whatsapp-evolution'
    | '/api/public/hooks/learning-patterns'
    | '/api/public/hooks/lembretes'
    | '/api/public/hooks/whatsapp-health'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp-evolution/health'
    | '/api/public/whatsapp-evolution/test'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/acessos'
    | '/_authenticated/agendar'
    | '/_authenticated/agentes-whatsapp'
    | '/_authenticated/aprendizado-ia'
    | '/_authenticated/assinantes'
    | '/_authenticated/assinatura'
    | '/_authenticated/auditoria-sugestoes'
    | '/_authenticated/base-conhecimento'
    | '/_authenticated/boas-vindas'
    | '/_authenticated/configuracao-whatsapp'
    | '/_authenticated/crm'
    | '/_authenticated/integracao-bemp'
    | '/_authenticated/operadores'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/permissoes'
    | '/_authenticated/sugestoes'
    | '/_authenticated/usuarios'
    | '/api/chat'
    | '/api/transcribe'
    | '/api/tts'
    | '/checkout/return'
    | '/index/old'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/bemp-webhook'
    | '/api/public/crm-cron'
    | '/api/public/test-ia'
    | '/api/public/whatsapp'
    | '/api/public/whatsapp-evolution'
    | '/api/public/hooks/learning-patterns'
    | '/api/public/hooks/lembretes'
    | '/api/public/hooks/whatsapp-health'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp-evolution/health'
    | '/api/public/whatsapp-evolution/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  IndexOldRoute: typeof IndexOldRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicBempWebhookRoute: typeof ApiPublicBempWebhookRoute
  ApiPublicCrmCronRoute: typeof ApiPublicCrmCronRoute
  ApiPublicTestIaRoute: typeof ApiPublicTestIaRoute
  ApiPublicWhatsappRoute: typeof ApiPublicWhatsappRoute
  ApiPublicWhatsappEvolutionRoute: typeof ApiPublicWhatsappEvolutionRouteWithChildren
  ApiPublicHooksLearningPatternsRoute: typeof ApiPublicHooksLearningPatternsRoute
  ApiPublicHooksLembretesRoute: typeof ApiPublicHooksLembretesRoute
  ApiPublicHooksWhatsappHealthRoute: typeof ApiPublicHooksWhatsappHealthRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/old': {
      id: '/index/old'
      path: '/index/old'
      fullPath: '/index/old'
      preLoaderRoute: typeof IndexOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sugestoes': {
      id: '/_authenticated/sugestoes'
      path: '/sugestoes'
      fullPath: '/sugestoes'
      preLoaderRoute: typeof AuthenticatedSugestoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissoes': {
      id: '/_authenticated/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof AuthenticatedPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operadores': {
      id: '/_authenticated/operadores'
      path: '/operadores'
      fullPath: '/operadores'
      preLoaderRoute: typeof AuthenticatedOperadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracao-bemp': {
      id: '/_authenticated/integracao-bemp'
      path: '/integracao-bemp'
      fullPath: '/integracao-bemp'
      preLoaderRoute: typeof AuthenticatedIntegracaoBempRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracao-whatsapp': {
      id: '/_authenticated/configuracao-whatsapp'
      path: '/configuracao-whatsapp'
      fullPath: '/configuracao-whatsapp'
      preLoaderRoute: typeof AuthenticatedConfiguracaoWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boas-vindas': {
      id: '/_authenticated/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/boas-vindas'
      preLoaderRoute: typeof AuthenticatedBoasVindasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento': {
      id: '/_authenticated/base-conhecimento'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria-sugestoes': {
      id: '/_authenticated/auditoria-sugestoes'
      path: '/auditoria-sugestoes'
      fullPath: '/auditoria-sugestoes'
      preLoaderRoute: typeof AuthenticatedAuditoriaSugestoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinantes': {
      id: '/_authenticated/assinantes'
      path: '/assinantes'
      fullPath: '/assinantes'
      preLoaderRoute: typeof AuthenticatedAssinantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprendizado-ia': {
      id: '/_authenticated/aprendizado-ia'
      path: '/aprendizado-ia'
      fullPath: '/aprendizado-ia'
      preLoaderRoute: typeof AuthenticatedAprendizadoIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agentes-whatsapp': {
      id: '/_authenticated/agentes-whatsapp'
      path: '/agentes-whatsapp'
      fullPath: '/agentes-whatsapp'
      preLoaderRoute: typeof AuthenticatedAgentesWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agendar': {
      id: '/_authenticated/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AuthenticatedAgendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acessos': {
      id: '/_authenticated/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AuthenticatedAcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-evolution': {
      id: '/api/public/whatsapp-evolution'
      path: '/api/public/whatsapp-evolution'
      fullPath: '/api/public/whatsapp-evolution'
      preLoaderRoute: typeof ApiPublicWhatsappEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp': {
      id: '/api/public/whatsapp'
      path: '/api/public/whatsapp'
      fullPath: '/api/public/whatsapp'
      preLoaderRoute: typeof ApiPublicWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-ia': {
      id: '/api/public/test-ia'
      path: '/api/public/test-ia'
      fullPath: '/api/public/test-ia'
      preLoaderRoute: typeof ApiPublicTestIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm-cron': {
      id: '/api/public/crm-cron'
      path: '/api/public/crm-cron'
      fullPath: '/api/public/crm-cron'
      preLoaderRoute: typeof ApiPublicCrmCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bemp-webhook': {
      id: '/api/public/bemp-webhook'
      path: '/api/public/bemp-webhook'
      fullPath: '/api/public/bemp-webhook'
      preLoaderRoute: typeof ApiPublicBempWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-evolution/test': {
      id: '/api/public/whatsapp-evolution/test'
      path: '/test'
      fullPath: '/api/public/whatsapp-evolution/test'
      preLoaderRoute: typeof ApiPublicWhatsappEvolutionTestRouteImport
      parentRoute: typeof ApiPublicWhatsappEvolutionRoute
    }
    '/api/public/whatsapp-evolution/health': {
      id: '/api/public/whatsapp-evolution/health'
      path: '/health'
      fullPath: '/api/public/whatsapp-evolution/health'
      preLoaderRoute: typeof ApiPublicWhatsappEvolutionHealthRouteImport
      parentRoute: typeof ApiPublicWhatsappEvolutionRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-health': {
      id: '/api/public/hooks/whatsapp-health'
      path: '/api/public/hooks/whatsapp-health'
      fullPath: '/api/public/hooks/whatsapp-health'
      preLoaderRoute: typeof ApiPublicHooksWhatsappHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lembretes': {
      id: '/api/public/hooks/lembretes'
      path: '/api/public/hooks/lembretes'
      fullPath: '/api/public/hooks/lembretes'
      preLoaderRoute: typeof ApiPublicHooksLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/learning-patterns': {
      id: '/api/public/hooks/learning-patterns'
      path: '/api/public/hooks/learning-patterns'
      fullPath: '/api/public/hooks/learning-patterns'
      preLoaderRoute: typeof ApiPublicHooksLearningPatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcessosRoute: typeof AuthenticatedAcessosRoute
  AuthenticatedAgendarRoute: typeof AuthenticatedAgendarRoute
  AuthenticatedAgentesWhatsappRoute: typeof AuthenticatedAgentesWhatsappRoute
  AuthenticatedAprendizadoIaRoute: typeof AuthenticatedAprendizadoIaRoute
  AuthenticatedAssinantesRoute: typeof AuthenticatedAssinantesRoute
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedAuditoriaSugestoesRoute: typeof AuthenticatedAuditoriaSugestoesRoute
  AuthenticatedBaseConhecimentoRoute: typeof AuthenticatedBaseConhecimentoRoute
  AuthenticatedBoasVindasRoute: typeof AuthenticatedBoasVindasRoute
  AuthenticatedConfiguracaoWhatsappRoute: typeof AuthenticatedConfiguracaoWhatsappRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedIntegracaoBempRoute: typeof AuthenticatedIntegracaoBempRoute
  AuthenticatedOperadoresRoute: typeof AuthenticatedOperadoresRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPermissoesRoute: typeof AuthenticatedPermissoesRoute
  AuthenticatedSugestoesRoute: typeof AuthenticatedSugestoesRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcessosRoute: AuthenticatedAcessosRoute,
  AuthenticatedAgendarRoute: AuthenticatedAgendarRoute,
  AuthenticatedAgentesWhatsappRoute: AuthenticatedAgentesWhatsappRoute,
  AuthenticatedAprendizadoIaRoute: AuthenticatedAprendizadoIaRoute,
  AuthenticatedAssinantesRoute: AuthenticatedAssinantesRoute,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedAuditoriaSugestoesRoute: AuthenticatedAuditoriaSugestoesRoute,
  AuthenticatedBaseConhecimentoRoute: AuthenticatedBaseConhecimentoRoute,
  AuthenticatedBoasVindasRoute: AuthenticatedBoasVindasRoute,
  AuthenticatedConfiguracaoWhatsappRoute:
    AuthenticatedConfiguracaoWhatsappRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedIntegracaoBempRoute: AuthenticatedIntegracaoBempRoute,
  AuthenticatedOperadoresRoute: AuthenticatedOperadoresRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPermissoesRoute: AuthenticatedPermissoesRoute,
  AuthenticatedSugestoesRoute: AuthenticatedSugestoesRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicWhatsappEvolutionRouteChildren {
  ApiPublicWhatsappEvolutionHealthRoute: typeof ApiPublicWhatsappEvolutionHealthRoute
  ApiPublicWhatsappEvolutionTestRoute: typeof ApiPublicWhatsappEvolutionTestRoute
}

const ApiPublicWhatsappEvolutionRouteChildren: ApiPublicWhatsappEvolutionRouteChildren =
  {
    ApiPublicWhatsappEvolutionHealthRoute:
      ApiPublicWhatsappEvolutionHealthRoute,
    ApiPublicWhatsappEvolutionTestRoute: ApiPublicWhatsappEvolutionTestRoute,
  }

const ApiPublicWhatsappEvolutionRouteWithChildren =
  ApiPublicWhatsappEvolutionRoute._addFileChildren(
    ApiPublicWhatsappEvolutionRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  IndexOldRoute: IndexOldRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicBempWebhookRoute: ApiPublicBempWebhookRoute,
  ApiPublicCrmCronRoute: ApiPublicCrmCronRoute,
  ApiPublicTestIaRoute: ApiPublicTestIaRoute,
  ApiPublicWhatsappRoute: ApiPublicWhatsappRoute,
  ApiPublicWhatsappEvolutionRoute: ApiPublicWhatsappEvolutionRouteWithChildren,
  ApiPublicHooksLearningPatternsRoute: ApiPublicHooksLearningPatternsRoute,
  ApiPublicHooksLembretesRoute: ApiPublicHooksLembretesRoute,
  ApiPublicHooksWhatsappHealthRoute: ApiPublicHooksWhatsappHealthRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
